#!/bin/sh
# Docker entrypoint script for Resgrid Dispatch Web
# This script substitutes environment variables into the env-config.js file at container startup

set -e

# Define the paths
OUTPUT_FILE="/usr/share/nginx/html/env-config.js"
INDEX_HTML="/usr/share/nginx/html/index.html"

# Set default values for environment variables if not provided
export DISPATCH_BASE_API_URL="${DISPATCH_BASE_API_URL:-https://api.resgrid.com}"
export DISPATCH_API_VERSION="${DISPATCH_API_VERSION:-v4}"
export DISPATCH_RESGRID_API_URL="${DISPATCH_RESGRID_API_URL:-/api/v4}"
export DISPATCH_CHANNEL_HUB_NAME="${DISPATCH_CHANNEL_HUB_NAME:-eventingHub}"
export DISPATCH_REALTIME_GEO_HUB_NAME="${DISPATCH_REALTIME_GEO_HUB_NAME:-geolocationHub}"
export DISPATCH_LOGGING_KEY="${DISPATCH_LOGGING_KEY:-}"
export DISPATCH_APP_KEY="${DISPATCH_APP_KEY:-}"
export DISPATCH_MAPBOX_PUBKEY="${DISPATCH_MAPBOX_PUBKEY:-}"
export DISPATCH_SENTRY_DSN="${DISPATCH_SENTRY_DSN:-}"
export DISPATCH_COUNTLY_APP_KEY="${DISPATCH_COUNTLY_APP_KEY:-}"
export DISPATCH_COUNTLY_SERVER_URL="${DISPATCH_COUNTLY_SERVER_URL:-}"
export DISPATCH_MAINTENANCE_MODE="${DISPATCH_MAINTENANCE_MODE:-false}"

# Function to JSON-encode a string value for safe JS interpolation
# Escapes backslashes, double quotes, single quotes, newlines, carriage returns, and tabs
json_encode_string() {
  local value="$1"
  # Use printf and sed to escape special characters
  # Order matters: escape backslashes first, then other characters
  printf '%s' "$value" | sed \
    -e 's/\\/\\\\/g' \
    -e 's/"/\\"/g' \
    -e "s/'/\\\\'/g" \
    -e 's/\t/\\t/g' \
    -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g' \
    -e 's/\r/\\r/g'
}

# Sanitize all DISPATCH_* environment variables for safe JS string interpolation
SAFE_BASE_API_URL=$(json_encode_string "$DISPATCH_BASE_API_URL")
SAFE_API_VERSION=$(json_encode_string "$DISPATCH_API_VERSION")
SAFE_RESGRID_API_URL=$(json_encode_string "$DISPATCH_RESGRID_API_URL")
SAFE_CHANNEL_HUB_NAME=$(json_encode_string "$DISPATCH_CHANNEL_HUB_NAME")
SAFE_REALTIME_GEO_HUB_NAME=$(json_encode_string "$DISPATCH_REALTIME_GEO_HUB_NAME")
SAFE_LOGGING_KEY=$(json_encode_string "$DISPATCH_LOGGING_KEY")
SAFE_APP_KEY=$(json_encode_string "$DISPATCH_APP_KEY")
SAFE_MAPBOX_PUBKEY=$(json_encode_string "$DISPATCH_MAPBOX_PUBKEY")
SAFE_SENTRY_DSN=$(json_encode_string "$DISPATCH_SENTRY_DSN")
SAFE_COUNTLY_APP_KEY=$(json_encode_string "$DISPATCH_COUNTLY_APP_KEY")
SAFE_COUNTLY_SERVER_URL=$(json_encode_string "$DISPATCH_COUNTLY_SERVER_URL")

# Normalize and validate MAINTENANCE_MODE as a boolean
# Only accept exactly "true" or "false", default to false with a warning for invalid values
case "$DISPATCH_MAINTENANCE_MODE" in
  true)
    SAFE_MAINTENANCE_MODE="true"
    ;;
  false)
    SAFE_MAINTENANCE_MODE="false"
    ;;
  *)
    echo "WARNING: Invalid DISPATCH_MAINTENANCE_MODE value: '$DISPATCH_MAINTENANCE_MODE'. Expected 'true' or 'false'. Defaulting to false." >&2
    SAFE_MAINTENANCE_MODE="false"
    ;;
esac

# Create the env-config.js with sanitized values
cat > "$OUTPUT_FILE" << EOF
/**
 * Runtime Environment Configuration for Web
 * Generated at container startup time
 * DO NOT EDIT - This file is auto-generated by docker-entrypoint.sh
 */
window.__ENV__ = {
  BASE_API_URL: '${SAFE_BASE_API_URL}',
  API_VERSION: '${SAFE_API_VERSION}',
  RESGRID_API_URL: '${SAFE_RESGRID_API_URL}',
  CHANNEL_HUB_NAME: '${SAFE_CHANNEL_HUB_NAME}',
  REALTIME_GEO_HUB_NAME: '${SAFE_REALTIME_GEO_HUB_NAME}',
  LOGGING_KEY: '${SAFE_LOGGING_KEY}',
  APP_KEY: '${SAFE_APP_KEY}',
  MAPBOX_PUBKEY: '${SAFE_MAPBOX_PUBKEY}',
  SENTRY_DSN: '${SAFE_SENTRY_DSN}',
  COUNTLY_APP_KEY: '${SAFE_COUNTLY_APP_KEY}',
  COUNTLY_SERVER_URL: '${SAFE_COUNTLY_SERVER_URL}',
  MAINTENANCE_MODE: ${SAFE_MAINTENANCE_MODE},
  IS_MOBILE_APP: false
};
EOF

echo "Generated env-config.js with runtime environment variables"

# Inject env-config.js script tag into index.html if not already present
if [ -f "$INDEX_HTML" ]; then
  if ! grep -q "env-config.js" "$INDEX_HTML"; then
    # Insert env-config.js script tag right after the opening <head> tag
    sed -i 's|<head>|<head>\n    <script src="/env-config.js"></script>|' "$INDEX_HTML"
    echo "Injected env-config.js script tag into index.html"
  else
    echo "env-config.js script tag already present in index.html"
  fi
fi

# Execute the original CMD (nginx)
exec "$@"
